### ISSUE TITLE
g2p is not installed

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-docker#28]
on a vanilla installation, docker on debian12, on which I just runned the ``docker compose --project-name ovos up -d`` command I get this error:

```
2023-08-21 09:47:42.113 - audio - ovos_plugin_manager.g2p:create:142 - ERROR - The selected G2P plugin could not be loaded.
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
          ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
2023-08-21 09:47:42.114 - audio - ovos_plugin_manager.templates.tts:__init__:448 - ERROR - G2P plugin not loaded, there will be no mouth movements
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 446, in __init__
    self.g2p = OVOSG2PFactory.create(cfg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
          ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

```

I have the same on my M1

**Comment by goldyfruit** [comment]
Same for me, I opened an issue about that yesterday here: https://github.com/NeonGeckoCom/neon-g2p-plugin-mimic/issues/1

**Comment by JarbasAl** [comment]
> Same for me, I opened an issue about that yesterday here: [NeonGeckoCom/neon-g2p-plugin-mimic#1](https://github.com/NeonGeckoCom/neon-g2p-plugin-mimic/issues/1)

wrong repo, ovos mimic G2P comes with the vanilla mimic1 plugin

**Comment by goldyfruit** [comment]
> > Same for me, I opened an issue about that yesterday here: [NeonGeckoCom/neon-g2p-plugin-mimic#1](https://github.com/NeonGeckoCom/neon-g2p-plugin-mimic/issues/1)
> 
> wrong repo, ovos mimic G2P comes with the vanilla mimic1 plugin

So I should remove `neon-g2p-plugin-mimic` as it's handled by https://github.com/OpenVoiceOS/ovos-tts-plugin-mimic/blob/406dc5f7431268d880435a27325523e29545e22e/ovos_tts_plugin_mimic/__init__.py#L24-L76 ?

**Comment by JarbasAl** [comment]
> > > Same for me, I opened an issue about that yesterday here: [NeonGeckoCom/neon-g2p-plugin-mimic#1](https://github.com/NeonGeckoCom/neon-g2p-plugin-mimic/issues/1)
> > 
> > 
> > wrong repo, ovos mimic G2P comes with the vanilla mimic1 plugin
> 
> So I should remove `neon-g2p-plugin-mimic` as it's handled by [OpenVoiceOS/ovos-tts-plugin-mimic@`406dc5f`/ovos_tts_plugin_mimic/__init__.py#L24-L76](https://github.com/OpenVoiceOS/ovos-tts-plugin-mimic/blob/406dc5f7431268d880435a27325523e29545e22e/ovos_tts_plugin_mimic/__init__.py#L24-L76) ?

yep

**Comment by goldyfruit** [comment]
Same without Neon plugin.

```
2023-08-21 11:55:43.217 - audio - ovos_plugin_manager.g2p:create:142 - ERROR - The selected G2P plugin could not be loaded.
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
          ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
2023-08-21 11:55:43.218 - audio - ovos_plugin_manager.templates.tts:__init__:448 - ERROR - G2P plugin not loaded, there will be no mouth movements
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 446, in __init__
    self.g2p = OVOSG2PFactory.create(cfg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
          ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by JarbasAl** [comment]
what is in mycroft.conf ?

**Comment by goldyfruit** [comment]
> what is in mycroft.conf ?

Nothing specific related to `g2p` (except the default configuration https://github.com/OpenVoiceOS/ovos-config/blob/dev/ovos_config/mycroft.conf#L648), should I add something?

**Comment by JarbasAl** [comment]
is ovos-classifiers installed? thats what provides the plugin

**Comment by goldyfruit** [comment]
> is ovos-classifiers installed? thats what provides the plugin

Indeed, adding `ovos-classifiers` to `ovos_audio` container solved the issue. :+1:

**Comment by goldyfruit** [comment]
@denics new `ovos_audio` image available with the fix.
