### ISSUE TITLE
ovos-gui-plugin-shell-companion missing in gui_websocket container?

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-docker#35]
Saw the below in the DEBUG logs;

```
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: 2023-09-05 11:32:28.069 - gui - ovos_plugin_manager.utils.config:get_plugin_config:38 - DEBUG - Loaded configuration: {'module': 'ovos-gui-plugin-shell-companion', 'idle_display_skill>
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: 2023-09-05 11:32:28.080 - gui - ovos_bus_client.session:from_message:490 - DEBUG - Creating default session on reference
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: 2023-09-05 11:32:28.084 - gui - ovos_plugin_manager.utils.config:get_plugin_config:38 - DEBUG - Loaded configuration: {'module': 'ovos-gui-plugin-shell-companion', 'idle_display_skill>
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: 2023-09-05 11:32:28.087 - gui - ovos_bus_client.session:reset_default_session:531 - INFO - New Default Session Start: 42bb7f0b-cfa9-47a9-a559-7f92db79251a
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: 2023-09-05 11:32:28.132 - gui - ovos_plugin_manager.utils:load_plugin:145 - WARNING - Could not find the plugin PluginTypes.GUI.ovos-gui-plugin-shell-companion
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: 2023-09-05 11:32:28.135 - gui - ovos_plugin_manager.gui:create:109 - ERROR - The selected gui plugin could not be loaded.
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: Traceback (most recent call last):
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/gui.py", line 106, in create
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:     gui = clazz(gui_config, bus=bus, gui=gui)
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: TypeError: 'NoneType' object is not callable
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: 2023-09-05 11:32:28.137 - gui - ovos_gui.extensions:activate_extension:52 - ERROR - failed to load ovos-gui-plugin-shell-companion, falling back to 'generic'
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: Traceback (most recent call last):
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_gui/extensions.py", line 48, in activate_extension
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:     self.extension = OVOSGuiFactory.create(cfg, bus=self.bus)
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/gui.py", line 106, in create
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:     gui = clazz(gui_config, bus=bus, gui=gui)
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 05 11:32:28 OpenVoiceOS ovos_gui_websocket[572]: TypeError: 'NoneType' object is not callable
```

**Comment by goldyfruit** [comment]
Thanks, fixed by https://github.com/OpenVoiceOS/ovos-docker/commit/3a08fbc22ef73fae5d6337bdb0de1eb01396d0d1 :+1:  

New image has been pushed.
